/// All countries available for the "Trending Now" country picker.
/// Each entry is (countryCode, displayLabel).
const kAllCountries = <(String, String)>[
  ('us', '🇺🇸 US'),
  ('gb', '🇬🇧 UK'),
  ('jp', '🇯🇵 Japan'),
  ('kr', '🇰🇷 Korea'),
  ('in', '🇮🇳 India'),
  ('de', '🇩🇪 Germany'),
  ('fr', '🇫🇷 France'),
  ('ca', '🇨🇦 Canada'),
  ('au', '🇦🇺 Australia'),
  ('br', '🇧🇷 Brazil'),
  ('mx', '🇲🇽 Mexico'),
  ('it', '🇮🇹 Italy'),
  ('es', '🇪🇸 Spain'),
  ('nl', '🇳🇱 Netherlands'),
  ('se', '🇸🇪 Sweden'),
  ('no', '🇳🇴 Norway'),
  ('dk', '🇩🇰 Denmark'),
  ('fi', '🇫🇮 Finland'),
  ('pl', '🇵🇱 Poland'),
  ('pt', '🇵🇹 Portugal'),
  ('at', '🇦🇹 Austria'),
  ('ch', '🇨🇭 Switzerland'),
  ('be', '🇧🇪 Belgium'),
  ('ie', '🇮🇪 Ireland'),
  ('nz', '🇳🇿 New Zealand'),
  ('sg', '🇸🇬 Singapore'),
  ('my', '🇲🇾 Malaysia'),
  ('th', '🇹🇭 Thailand'),
  ('ph', '🇵🇭 Philippines'),
  ('id', '🇮🇩 Indonesia'),
  ('vn', '🇻🇳 Vietnam'),
  ('tw', '🇹🇼 Taiwan'),
  ('ru', '🇷🇺 Russia'),
  ('tr', '🇹🇷 Turkey'),
  ('sa', '🇸🇦 Saudi Arabia'),
  ('ae', '🇦🇪 UAE'),
  ('eg', '🇪🇬 Egypt'),
  ('ng', '🇳🇬 Nigeria'),
  ('za', '🇿🇦 South Africa'),
  ('ar', '🇦🇷 Argentina'),
  ('co', '🇨🇴 Colombia'),
  ('cl', '🇨🇱 Chile'),
  ('il', '🇮🇱 Israel'),
  ('pk', '🇵🇰 Pakistan'),
  ('bd', '🇧🇩 Bangladesh'),
  ('cz', '🇨🇿 Czech Republic'),
  ('hu', '🇭🇺 Hungary'),
  ('ro', '🇷🇴 Romania'),
  ('gr', '🇬🇷 Greece'),
];

/// The default set of country codes shown when no preference is saved.
const kDefaultHomeCountries = <String>['us', 'gb', 'jp', 'kr', 'in', 'de'];
